# Generated by Django 5.1.7 on 2025-03-25 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("min_age", models.IntegerField()),
                ("max_age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("extra_info", models.TextField(blank=True)),
                ("owner_id", models.CharField(max_length=50)),
                ("has_drawn", models.BooleanField(default=False)),
                ("is_drawn", models.BooleanField(default=False)),
                (
                    "age_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eidraw.agegroup",
                    ),
                ),
                (
                    "drawn_person",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eidraw.person",
                    ),
                ),
            ],
        ),
    ]
