# Generated by Django 5.1.7 on 2025-03-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='Person',
            name='gender',
            field= models.CharField(
                max_length=6,
                choices=[('MALE', 'Male'), ('FEMALE', 'Female')],
                default='MALE')
        )
    ]
