# Generated by Django 5.1.7 on 2025-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0002_auto_20250325_0510"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_price_limit",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
                ),
                ("drawing_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
