# Generated by Django 5.1.7 on 2025-03-27 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0003_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("organizer_id", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("drawing_enabled", models.BooleanField(default=False)),
                (
                    "gift_price_limit",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AddField(
            model_name="person",
            name="user_id",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="wishlist",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="drawn_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eidraw.person",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="exclusion",
            name="exclude",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excluded_by",
                to="eidraw.person",
            ),
        ),
        migrations.AddField(
            model_name="exclusion",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exclusions",
                to="eidraw.person",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="eidraw.group",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("group", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="exclusion",
            unique_together={("person", "exclude")},
        ),
        migrations.RemoveField(
            model_name="person",
            name="age_group",
        ),
        migrations.RemoveField(
            model_name="person",
            name="extra_info",
        ),
        migrations.RemoveField(
            model_name="person",
            name="owner_id",
        ),
    ]
