# Generated by Django 5.1.7 on 2025-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0004_exclusion_group_delete_settings_person_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="organizer_id",
        ),
        migrations.AddField(
            model_name="group",
            name="organizer_email",
            field=models.EmailField(default="admin@example.com", max_length=254),
            preserve_default=False,
        ),
    ]
