# Generated by Django 5.1.7 on 2025-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0005_remove_group_organizer_id_group_organizer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
    ]
