# Generated by Django 5.1.7 on 2025-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0006_alter_person_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="user_id",
            new_name="telegram_id",
        ),
        migrations.AddField(
            model_name="group",
            name="telegram_bot_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
    ]
