# Generated by Django 5.1.7 on 2025-03-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eidraw", "0007_rename_user_id_person_telegram_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="date",
        ),
        migrations.RemoveField(
            model_name="group",
            name="organizer_email",
        ),
        migrations.RemoveField(
            model_name="group",
            name="telegram_bot_token",
        ),
        migrations.AddField(
            model_name="group",
            name="organizer_telegram_id",
            field=models.CharField(default="teleid 1", max_length=100),
            preserve_default=False,
        ),
    ]
